version: '3.8'

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-XX:+UseZGC -Xmx1G -XX:+UseContainerSupport
    volumes:
      - ./target:/app/target
      - ./logs:/app/logs
    
  db:
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql